version: '3.8'

volumes:
  postgres-data-dev:

services:

  gateway:
    image: ${CADDY_IMAGE}
    container_name: gateway-dev
    volumes:
      - ./caddy/config/Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - frontend
      - server
    restart: unless-stopped

  postgres:
    image: ${POSTGRES_IMAGE}
    container_name: postgres-dev
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - ${DEV_POSTGRES_PORT}:5432
    volumes:
      - postgres-data-dev:/var/lib/postgresql/data
    restart: unless-stopped

  server:
    container_name: server-dev
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    volumes:
      - ./server:/app
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}
      - USERS_ACCESS_TOKEN_SECRET=${USERS_ACCESS_TOKEN_SECRET}
    ports:
      - ${DEV_SERVER_PORT}:3000
    restart: unless-stopped

  frontend:
    container_name: frontend-dev
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
    ports:
      - ${DEV_FRONTEND_PORT}:3000
    depends_on:
      - server
    restart: unless-stopped

  console:
    container_name: console-dev
    build:
      context: ./console
      dockerfile: Dockerfile.dev
    volumes:
      - ./console:/app
    ports:
      - ${DEV_CONSOLE_PORT}:3000
    depends_on:
      - server
    restart: unless-stopped
