version: '3.8'

services:

  cloud-proxy:
    build:
      context: cloud-proxy
    hostname: cloud-proxy
    container_name: cloud-proxy
    volumes:
      - ./cloud-proxy/Caddyfile:/etc/caddy/Caddyfile
    ports:
      - 80:80
      - 443:443
    depends_on:
      - gateway
    environment:
      - CLOUD_CONSOLE_URL=${CLOUD_CONSOLE_URL}
      - CLOUD_APP_WILDCARD_DOMAIN=${CLOUD_APP_WILDCARD_DOMAIN}
      - CLOUD_APP_WILDCARD_DOMAIN_DNS_API_KEY=${CLOUD_APP_WILDCARD_DOMAIN_DNS_API_KEY}
    restart: unless-stopped

  gateway:
    image: ${CADDY_IMAGE}
    hostname: gateway
    container_name: gateway
    volumes:
      - ./caddy/config/Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - frontend
      - server
    restart: unless-stopped

  postgres:
    image: ${POSTGRES_IMAGE}
    hostname: postgres
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  server:
    container_name: server
    hostname: server
    image: ${SERVER_IMAGE}
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}
      - USERS_ACCESS_TOKEN_SECRET=${USERS_ACCESS_TOKEN_SECRET}
    depends_on:
      - postgres
    restart: unless-stopped

  frontend:
    container_name: frontend
    hostname: frontend
    image: ${FRONTEND_IMAGE}
    depends_on:
      - server
    restart: unless-stopped

  console:
    container_name: console
    hostname: console
    image: ${CONSOLE_IMAGE}
    depends_on:
      - server
    restart: unless-stopped

volumes:
  postgres-data:
