version: '3.8'

volumes:
  postgres-data:

services:

  cloud-proxy:
    # TODO: build cloud proxy image in a pipeline and turn it into a proper package
    # Not urgent as this is used only to host the cloud version.
    build:
      context: cloud-proxy
    volumes:
      - ./cloud-proxy/Caddyfile:/etc/caddy/Caddyfile
    ports:
      - 80:80
      - 443:443
    depends_on:
      - gateway
    environment:
      - CLOUD_CONSOLE_URL=${CLOUD_CONSOLE_URL}
      - CLOUD_APP_WILDCARD_DOMAIN=${CLOUD_APP_WILDCARD_DOMAIN}
      - CLOUD_APP_WILDCARD_DOMAIN_DNS_API_KEY=${CLOUD_APP_WILDCARD_DOMAIN_DNS_API_KEY}
    restart: unless-stopped

  gateway:
    image: ${CADDY_IMAGE}
    volumes:
      - ./caddy/config/Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - frontend
      - server
    restart: unless-stopped

  postgres:
    image: ${POSTGRES_IMAGE}
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  server:
    image: ${SERVER_IMAGE}
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}
      - USERS_ACCESS_TOKEN_SECRET=${USERS_ACCESS_TOKEN_SECRET}
      - MEMBERS_ACCESS_TOKEN_SECRET=${MEMBERS_ACCESS_TOKEN_SECRET}
      - MEMBERS_AUTH_CODE_EXPIRATION_DELAY_IN_MINUTES=${MEMBERS_AUTH_CODE_EXPIRATION_DELAY_IN_MINUTES}
    depends_on:
      - postgres
    restart: unless-stopped

  frontend:
    image: ${FRONTEND_IMAGE}
    depends_on:
      - server
    restart: unless-stopped

  console:
    image: ${CONSOLE_IMAGE}
    depends_on:
      - server
    restart: unless-stopped
